CREATE TABLE IF NOT EXISTS User (
    id VARCHAR(255) PRIMARY KEY,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB;